# -*- coding: utf-8 -*-
"""preparcial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7-UPbiFS9Jv_5qB3BKWBp8f78MVPoUN

### PREPARCIAL

Escriba un programa que pregunte al usuario un día de la semana y una hora del día entre las 6 y las 22 hrs y muestre la actividad que tiene ese día basado en la siguiente tabla, en los espacios vacíos deberá mostrar: "libre", además, el programa deberá discriminar los datos, si son numéricos y letras para el día
y la hora; el día de la semana debe ser el nombre completo o bien: Lunes =>L, Martes =>M, Miércoles =>Mc, Jueves =>J, Viernes =>V.
"""

import numpy as np

rutina = np.array([[6,7,"Gym","Gym","Libre","Gym","Gym"],
                  [8,9,"Reunión","Cita Medica","Reunión","Libre","Libre"],
                  [10,11,"Asesoría","Libre","Libre","Fondo de Inversión","Comité Cuántico"],
                  [12,13,"Almuerzo","Almuerzo","Almuerzo","Almuerzo","Almuerzo"],
                  [14,15,"Consultoría","Libre","Ventas y suministros","Géstion de Calidad","Libre"],
                  [16,17,"Tutorías","Libre","Libre","Reunión Talento Humano","Libre"],
                  [18,19,"Matemáticas III","Métodos Numéricos","Matemáticas III","Métodos Numéicos","Tesis"],
                  [20,21,"Sistemas Dinámicos","Inteligencia Artificial","Sistemas Dinamicos","Inteligencia Artificial","Farra"]])
print("Tabla:\n",rutina)

bandera=False
while bandera==False:

  dia=str.capitalize(input("Dia:"))
  print(dia)
  hora=input("Hora:") 
  
  if dia.isalpha() and hora.isnumeric():
    num=int(hora)
    if num >=6 and num<=21:

      if dia=="Lunes":     
        for fila in range(len(rutina[0])+1):        
          for columna in range(len(rutina[:2])):
            if rutina[fila,columna]==hora:
              print("El dia ",dia," a la hora ",hora,"Esta ",rutina[fila,2])
        bandera=True

      elif dia=="Martes":
        for fila in range(len(rutina[0])+1):        
          for columna in range(len(rutina[:2])):
            if rutina[fila,columna]==hora:
              print("El dia ",dia," a la hora ",hora,"Esta ",rutina[fila,3])
        bandera=True

      elif dia=="Miercioles":
        for fila in range(len(rutina[0])+1):        
          for columna in range(len(rutina[:2])):
            if rutina[fila,columna]==hora:
              print("El dia ",dia," a la hora ",hora,"Esta ",rutina[fila,4])
        bandera=True

      elif dia=="Jueves":
        for fila in range(len(rutina[0])+1):        
          for columna in range(len(rutina[:2])):
            if rutina[fila,columna]==hora:
              print("El dia ",dia," a la hora ",hora,"Esta ",rutina[fila,5])
        bandera=True

      elif dia=="Viernes":
        for fila in range(len(rutina[0])+1):        
          for columna in range(len(rutina[:2])):
            if rutina[fila,columna]==hora:
              print("El dia ",dia," a la hora ",hora,"esta ",rutina[fila,6])
        bandera=True

      else:
        print("los dias van desde el lunes hasta el viernes")
        bandera=False  

    else:
      print("Solo ingresar horas entre las 6 y las 21")
      bandera=False
  else:
    print("Por Favor Ingresar datos correctos")
    bandera=False

