# -*- coding: utf-8 -*-
"""Taller 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yBMGVmP-J3aw8m87Xun6oFtQxCL5-OYW

# Taller 2
"""

import numpy as np
notas = np.array([4.3,4.2,1.5,3.5,2.0,2.2,3.5,4.8,5.0,0.0])
print(notas)
# para hallar el promedio de la notas se emplea la funcion np.mean
media = np.mean(notas)
print('media:',media)
# para hallar la desviacion estandar se emplea la funcion np.std
desviacion = np.std(notas)
print('Desviacion Estandar:',desviacion)
# para hallar la mediana estandar se emplea la funcion np.median
mediana = np.median(notas)
print('Mediana:',mediana)
orden = np.sort(notas)
print('Notas ordenadas:', orden)

"""## Punto 1
Investigue como utilizar el comando np.loadtxt o np.genfromtxt para importar datos desde un archivo .csv
a Python, importar los datos del archivo adjunto y calcular: la definitiva de las notas de cada uno de los
estudiantes si se sabe que N1, N2 y N3 se promedian y corresponden al 60 % del corte y el parcial es el
40 %.
"""

import numpy as np

notas2=np.genfromtxt("Notas.csv",delimiter = ',')
#Tabla de notas
print("tabla de notas:\n",notas2)
#calculo de promedio por notas y calculo de la definitiva
defi=(notas2[:,1:4].mean(axis=1)*0.6)+(notas2[:,4]*0.4)
print("Definitivas por estudiante:\n",defi)

"""## Punto 2
Encuentre la media, la desviación estándar y la mediana (recuerde que para este dato los números tiene
que estar ordenados de forma creciente) de las notas definitivas.
"""

import numpy as np
#Media
print("Media definitivas:",round(np.mean(defi),2))
#desviacion estandar
print("Desviacion estandar definitivas:",round(np.std(defi),2))
#Mediana
orden=np.sort(defi)
print("Definitivas ordenadas",orden)
print("Mediana definitivas:",round(np.median(defi),2))

"""## Punto 3

Hay tres estudiantes que estaban en el grupo de otro profesor y cuyas notas son:
|est|N1|N2|N3|PARCIAL|
|---|---|---|---|---|
|33|4.3|2.3|1.5|3.7|
|34|4.2|3.1|2.0|4.0|
|35|1.5|2.8|3.8|3.1|

Calcule la nota definitiva de cada uno, concatene los datos con los cargados anteriormente haciendo uso
de python y calcule de nuevo la media, la mediana y la desviación estándar. Puede ser util el comando
np.concatenate o np.vstack

"""

import numpy as np
notas3=np.array([[33,4.3,2.3,1.5,3.7],[34,4.2,3.1,2.0,4.0],[35,1.5,2.8,3.8,3.1]])
#Concatenar notas
notas4=np.concatenate((notas2,notas3),axis=0)
#Calcular definitivas
defi2=(notas4[:,1:4].mean(axis=1)*0.6)+(notas4[:,4]*0.4)
print(defi2)
#Media
print("Media definitivas:",round(np.mean(defi2),2))
#desviacion estandar
print("Desviacion estandar definitivas:",round(np.std(defi2),2))
#Mediana
orden2=np.sort(defi2)
print("Definitivas ordenadas",orden2)
print("Mediana definitivas:",round(np.median(defi2),2))

